spring:
  application:
    name: sohu.mq-cloud.local
  datasource:
    url: jdbc:h2:file:./mqcloud.db;MODE=MySQL;database_to_upper=false;NON_KEYWORDS=user;INIT=RUNSCRIPT FROM 'classpath:h2db/schema.sql'\;RUNSCRIPT FROM 'classpath:h2db/data.sql';
    driver-class-name: org.h2.Driver
  h2:
    console:
      enabled: true
  freemarker:
    cache: false